### ISSUE TITLE
Ardis Builder ? Arch Linux

### ISSUE THREAD

**Issue by MichaelTiebesl** [iJunkie22/Ardis-Builder#1]
I can't make Ardis Builder work in Arch Linux. Is there any help how to set it up?

**Comment by iJunkie22** [comment]
What exactly do you mean? Ardis Builder is a python package, so just `cd` into the containing directory, then just run 
`python ./setup.py install` (maybe as root if needed)
Once installed, just run this from wherever:
`python -m ardisBuilder`

If this works for you, let me know here so I can close the issue. If another issue occurs, open another issue ticket and I'm sure I'll be able to either explain the task or, if it is a bug, release a patch. My python experience is more than 4x the experience I had when I wrote ArdisBuilder, so I'm sure I'll have an answer! :)

**Comment by MichaelTiebesl** [comment]
Thanks for your time,

This is what i did before after what Ivan told me to do: "And if you wish to use ArdisBuilder to customize your icon pack, extract the content of 'ArdisBuilder.tar.gz' somewhere on your system, and run the script inside Ardis-Builder folder called 'make_loader.sh' if you wish to have launcher in your menu. That's it, open Ardis Builder and customize your icon pack, and then go and apply the icon theme using your desktop tool for applying icon themes."

That was the reason i made an issue here. The way above was not working for me.

After doing what you mention, i put Ardis Builder in /usr/share/icons, i did the steps with sudo.
I get this error after that: 
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/icons/Ardis-Builder/ardisBuilder/__main__.py", line 4, in <module>
    from . import ardisbuilderapp
  File "/usr/share/icons/Ardis-Builder/ardisBuilder/ardisbuilderapp.py", line 94
    print "%s items done" % self.counter
                        ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by iJunkie22** [comment]
First things first: ArdisBuilder is written for _python 2_, and **has not been ported to Python 3.x**. I have chosen to not take on porting, since 2 is still the most widely used, and the default on most linux distros when ArdisBuilder was written. Try running it with an interpreter that is within 2.7-2.9. 

To find which interpreters you have, 
run

``` bash
echo $PATH | tr ':' '\n' | sort -u | while read line; do (echo $line/pytho*) | tr ' ' '\n'; done | grep -v -E "(-config|\*|pythonw)" | while read pline; do echo "$pline"; ($pline --version); echo "======";done
```

**Comment by MichaelTiebesl** [comment]
This is what i get: 
usr/bin/python

# Python 3.4.3

usr/bin/python2

# Python 2.7.10

usr/bin/python2.7

# Python 2.7.10

usr/bin/python2-pyuic4

# Python User Interface Compiler 4.11.4 for Qt version 4.8.7

usr/bin/python3

# Python 3.4.3

usr/bin/python3.4

# Python 3.4.3

usr/bin/python3.4m
Python 3.4.3

**Comment by iJunkie22** [comment]
alright, given those choices, I recommend you run it like this:

``` bash
python2 ./setup.py install
```

``` bash
python2 -m ardisBuilder
```

**Comment by MichaelTiebesl** [comment]
Thanks, that did it. I can use the Ardis Builder now. I have installed Ardis Builder in /usr/share/icons
So it is installed with root. I don't see in my menu from Gnome the Ardis Builder. Is that because i have to installed it in home?

**Comment by iJunkie22** [comment]
Well, this all depends where your system keeps its launchers, but kind of. `.desktop` files really require an absolute path, so supplying one with something meant to be portable didn't really make sense. However, running the supplied `make_loader.sh` script _should_ make a `.desktop` file in a location that GNOME will look for it at. By the way, you say you are running Arch, right? Which release (I know Arch uses rolling releases so just a date or anything you can supply me with so I can specify what's supported here -> #2
